export const login = 'USER_LOGIN'
export const logout = 'USER_LOGOUT'
export const signup = 'USER_SIGNUP'
export const setLogin = 'USER_SET_LOGIN'
export const setLogout = 'USER_SET_LOGOUT'
export const getStatus = 'USER_GET_STATUS'